//! Python backend — emits [Hypothesis](https://hypothesis.readthedocs.io)
//! property tests that run under pytest.
//!
//! Correspondence is BY CONVENTION: the system-under-test module must expose a
//! class per sort (constructed with keyword args matching the sort's fields)
//! and a function per relation, using the same names as the `.tent` spec.

use std::collections::HashMap;

use super::{Backend, EmitOptions};
use crate::ast::*;

/// The Python / Hypothesis code generator.
pub struct PythonBackend;

impl Backend for PythonBackend {
    fn default_filename(&self) -> &'static str {
        "test_generated.py"
    }

    fn emit(&self, spec: &Spec, opts: &EmitOptions) -> String {
        let sorts: HashMap<&str, &Sort> = spec.sorts.iter().map(|s| (s.name.as_str(), s)).collect();

        let mut out = String::new();
        out.push_str("# @generated by rascador — do not edit by hand.\n");
        out.push_str("# Each test checks that a relation's implementation matches its law.\n");
        out.push_str("from hypothesis import given, strategies as st\n");
        out.push_str(&format!("import {} as sut\n\n\n", opts.module));

        for law in &spec.laws {
            out.push_str(&generate_law(law, spec, &sorts));
        }
        out
    }
}

fn generate_law(law: &Law, spec: &Spec, sorts: &HashMap<&str, &Sort>) -> String {
    let relation = spec
        .relations
        .iter()
        .find(|r| r.name == law.relation)
        .expect("checker guarantees the relation exists");

    let mut givens: Vec<String> = Vec::new(); // `name=st.integers(...)`
    let mut param_names: Vec<String> = Vec::new(); // function params, in order
    let mut constructs: Vec<String> = Vec::new(); // `p = sut.TemporalPoint(...)`
    let mut call_args: Vec<String> = Vec::new();

    for (arg, param) in law.args.iter().zip(&relation.params) {
        let sort = sorts
            .get(param.sort.as_str())
            .expect("checker guarantees the sort exists");

        if sort.fields.is_empty() {
            // Identity sort: a bare int is the value.
            givens.push(format!(
                "{arg}={}",
                strategy_for(&Ty::Sort(sort.name.clone()))
            ));
            param_names.push(arg.clone());
            call_args.push(arg.clone());
        } else {
            let mut kw_inits: Vec<String> = Vec::new();
            for field in &sort.fields {
                let pname = format!("{arg}_{}", field.name);
                givens.push(format!("{pname}={}", strategy_for(&field.ty)));
                param_names.push(pname.clone());
                kw_inits.push(format!("{}={pname}", field.name));
            }
            constructs.push(format!(
                "    {arg} = sut.{}({})",
                sort.name,
                kw_inits.join(", ")
            ));
            call_args.push(arg.clone());
        }
    }

    let oracle = if law.preds.is_empty() {
        "True".to_string()
    } else {
        law.preds
            .iter()
            .map(pred_to_py)
            .collect::<Vec<_>>()
            .join(" and ")
    };

    let mut body = String::new();
    body.push_str("@given(\n");
    for g in &givens {
        body.push_str(&format!("    {g},\n"));
    }
    body.push_str(")\n");
    body.push_str(&format!(
        "def test_law_{}({}):\n",
        law.relation,
        param_names.join(", ")
    ));
    for c in &constructs {
        body.push_str(c);
        body.push('\n');
    }
    body.push_str(&format!("    oracle = {oracle}\n"));
    body.push_str(&format!(
        "    actual = sut.{}({})\n",
        law.relation,
        call_args.join(", ")
    ));
    body.push_str("    assert actual == oracle\n\n\n");
    body
}

/// A Hypothesis strategy for a field type.
fn strategy_for(ty: &Ty) -> &'static str {
    match ty {
        Ty::Int => "st.integers(min_value=-20, max_value=20)",
        // No-field sort = an identity id in a tiny range so collisions (and
        // thus law violations) are likely to be hit.
        Ty::Sort(_) => "st.integers(min_value=0, max_value=1)",
    }
}

fn pred_to_py(pred: &Pred) -> String {
    format!(
        "({} {} {})",
        expr_to_py(&pred.lhs),
        op_to_py(pred.op),
        expr_to_py(&pred.rhs)
    )
}

fn expr_to_py(expr: &Expr) -> String {
    match expr {
        Expr::Field { arg, field } => format!("{arg}.{field}"),
        Expr::Int(n) => format!("{n}"),
        Expr::Arg(name) => name.clone(),
    }
}

fn op_to_py(op: CmpOp) -> &'static str {
    match op {
        CmpOp::Eq => "==",
        CmpOp::Le => "<=",
        CmpOp::Lt => "<",
        CmpOp::Ge => ">=",
        CmpOp::Gt => ">",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse;

    fn generate(src: &str, module: &str) -> String {
        let spec = parse(src).unwrap();
        PythonBackend.emit(
            &spec,
            &EmitOptions {
                module: module.to_string(),
            },
        )
    }

    #[test]
    fn generates_expected_pieces_for_real_spec() {
        let src = include_str!("../../../../.rascador/temporal.tent");
        let code = generate(src, "temporal");

        assert!(code.contains("from hypothesis import given, strategies as st"));
        assert!(code.contains("import temporal as sut"));
        assert!(code.contains("def test_law_point_in_interval("));
        // class construction with keyword args matching the spec's fields
        assert!(code.contains("p = sut.TemporalPoint(media=p_media, t=p_t)"));
        // oracle uses `and` and reflects point-in-interval
        assert!(code.contains("(p.media == i.media) and (i.t0 <= p.t) and (p.t <= i.t1)"));
        // calls the impl through the sut module
        assert!(code.contains("sut.point_in_interval(p, i)"));
        assert!(code.contains("assert actual == oracle"));
    }
}
