//! Rust backend — emits `proptest` tests.
//!
//! Correspondence is BY CONVENTION: the system-under-test crate must define a
//! struct per sort and a function per relation, using the same names and field
//! names as the `.tent` spec.

use std::collections::HashMap;

use super::{Backend, EmitOptions};
use crate::ast::*;

/// The Rust / proptest code generator.
pub struct RustBackend;

impl Backend for RustBackend {
    fn default_filename(&self) -> &'static str {
        "generated.rs"
    }

    fn emit(&self, spec: &Spec, opts: &EmitOptions) -> String {
        let sorts: HashMap<&str, &Sort> = spec.sorts.iter().map(|s| (s.name.as_str(), s)).collect();

        let mut out = String::new();
        out.push_str("// @generated by hiker — do not edit by hand.\n");
        out.push_str("// Each test checks that a relation's implementation matches its law.\n\n");
        out.push_str("use proptest::prelude::*;\n");
        out.push_str(&format!("use {}::*;\n\n", opts.module));

        out.push_str("proptest! {\n");
        for law in &spec.laws {
            out.push_str(&generate_law(law, spec, &sorts));
        }
        out.push_str("}\n");
        out
    }
}

fn generate_law(law: &Law, spec: &Spec, sorts: &HashMap<&str, &Sort>) -> String {
    // Find the relation so we know each argument's sort.
    let relation = spec
        .relations
        .iter()
        .find(|r| r.name == law.relation)
        .expect("checker guarantees the relation exists");

    // Build proptest parameter list and struct-construction statements.
    let mut params: Vec<String> = Vec::new();
    let mut constructs: Vec<String> = Vec::new();

    for (arg, param) in law.args.iter().zip(&relation.params) {
        let sort = sorts
            .get(param.sort.as_str())
            .expect("checker guarantees the sort exists");

        let mut field_inits: Vec<String> = Vec::new();
        for field in &sort.fields {
            let pname = format!("{arg}_{}", field.name);
            let (_rust_ty, strategy) = strategy_for(&field.ty, sorts);
            params.push(format!("{pname} in {strategy}"));
            field_inits.push(format!("{}: {pname}", field.name));
        }

        if field_inits.is_empty() {
            // A sort with no fields is an identity value (a u32 id).
            params.push(format!("{arg} in 0u32..3"));
            // No struct to build; the bare id is the value.
        } else {
            constructs.push(format!(
                "        let {arg} = {} {{ {} }};",
                sort.name,
                field_inits.join(", ")
            ));
        }
    }

    // The oracle: AND of all clauses (or `true` if there are none).
    let oracle = if law.clauses.is_empty() {
        "true".to_string()
    } else {
        law.clauses
            .iter()
            .map(clause_to_rust)
            .collect::<Vec<_>>()
            .join(" && ")
    };

    // The implementation call passes each argument by reference.
    let call_args = law
        .args
        .iter()
        .map(|a| format!("&{a}"))
        .collect::<Vec<_>>()
        .join(", ");

    let mut body = String::new();
    body.push_str(&format!("    #[test]\n    fn law_{}(\n", law.relation));
    for p in &params {
        body.push_str(&format!("        {p},\n"));
    }
    body.push_str("    ) {\n");
    for c in &constructs {
        body.push_str(c);
        body.push('\n');
    }
    body.push_str(&format!("        let oracle = {oracle};\n"));
    body.push_str(&format!(
        "        let actual = {}({call_args});\n",
        law.relation
    ));
    body.push_str("        prop_assert_eq!(actual, oracle);\n");
    body.push_str("    }\n\n");
    body
}

/// Pick a Rust type and a proptest strategy for a field type.
fn strategy_for(ty: &Ty, sorts: &HashMap<&str, &Sort>) -> (&'static str, &'static str) {
    match ty {
        // Ranges are deliberately small: tight ranges make random collisions
        // (and thus law violations) likely to be hit, and shrink to clean,
        // readable counterexamples.
        Ty::Int => ("i64", "-20i64..20i64"),
        Ty::Sort(_name) => {
            // A field whose type is a no-field sort is an identity id (u32).
            // (Nested structs with fields are out of scope for v0.)
            let _ = sorts; // kept for future nested-struct support
            ("u32", "0u32..2u32")
        }
    }
}

fn clause_to_rust(clause: &Clause) -> String {
    match clause {
        Clause::Compare(p) => pred_to_rust(p),
        // `antecedent => consequent` is logically `(!antecedent || consequent)`.
        Clause::Implies { ante, cons, .. } => {
            format!("(!{} || {})", pred_to_rust(ante), pred_to_rust(cons))
        }
    }
}

fn pred_to_rust(pred: &Pred) -> String {
    format!(
        "({} {} {})",
        expr_to_rust(&pred.lhs),
        op_to_rust(pred.op),
        expr_to_rust(&pred.rhs)
    )
}

fn expr_to_rust(expr: &Expr) -> String {
    match expr {
        Expr::Field { arg, field } => format!("{arg}.{field}"),
        Expr::Int(n) => format!("{n}i64"),
        Expr::Arg(name) => name.clone(),
    }
}

fn op_to_rust(op: CmpOp) -> &'static str {
    match op {
        CmpOp::Eq => "==",
        CmpOp::Le => "<=",
        CmpOp::Lt => "<",
        CmpOp::Ge => ">=",
        CmpOp::Gt => ">",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse;

    fn generate(spec: &Spec, module: &str) -> String {
        RustBackend.emit(
            spec,
            &EmitOptions {
                module: module.to_string(),
            },
        )
    }

    #[test]
    fn generates_expected_pieces_for_real_spec() {
        let src = include_str!("../../../../.hiker/temporal.tent");
        let spec = parse(src).unwrap();
        let code = generate(&spec, "temporal");

        // imports
        assert!(code.contains("use proptest::prelude::*;"));
        assert!(code.contains("use temporal::*;"));
        // one test per law
        assert!(code.contains("fn law_temporal_overlap("));
        assert!(code.contains("fn law_point_in_interval("));
        // struct construction with the spec's field names
        assert!(code.contains("TemporalPoint { media: p_media, t: p_t }"));
        // oracle reflects the point-in-interval law (not interval overlap)
        assert!(code.contains("(i.t0 <= p.t) && (p.t <= i.t1)"));
        // calls the real impl by reference
        assert!(code.contains("point_in_interval(&p, &i)"));
        assert!(code.contains("prop_assert_eq!(actual, oracle);"));
    }

    #[test]
    fn implication_lowers_to_or_not() {
        let src = "\
sort Tag
sort E { tag: Tag, status: Int }
relation det(a: E, b: E)
law det(a, b) {
  a.tag == b.tag => a.status == b.status
}";
        let spec = parse(src).unwrap();
        let code = generate(&spec, "e");
        assert!(code.contains("(!(a.tag == b.tag) || (a.status == b.status))"));
    }
}
