//! TypeScript backend — emits [fast-check](https://fast-check.dev) property
//! tests that run under vitest.
//!
//! Correspondence is BY CONVENTION: the system-under-test module must export a
//! function per relation, taking plain objects whose fields match the sort's
//! fields in the `.tent` spec.

use std::collections::HashMap;

use super::{Backend, EmitOptions};
use crate::ast::*;

/// The TypeScript / fast-check code generator.
pub struct TypeScriptBackend;

impl Backend for TypeScriptBackend {
    fn default_filename(&self) -> &'static str {
        "generated.test.ts"
    }

    fn emit(&self, spec: &Spec, opts: &EmitOptions) -> String {
        let sorts: HashMap<&str, &Sort> = spec.sorts.iter().map(|s| (s.name.as_str(), s)).collect();

        let mut out = String::new();
        out.push_str("// @generated by hiker — do not edit by hand.\n");
        out.push_str("// Each test checks that a relation's implementation matches its law.\n");
        out.push_str("import { test } from \"vitest\";\n");
        out.push_str("import fc from \"fast-check\";\n");
        out.push_str(&format!("import * as sut from \"{}\";\n\n", opts.module));

        for law in &spec.laws {
            out.push_str(&generate_law(law, spec, &sorts));
        }
        out
    }
}

fn generate_law(law: &Law, spec: &Spec, sorts: &HashMap<&str, &Sort>) -> String {
    let relation = spec
        .relations
        .iter()
        .find(|r| r.name == law.relation)
        .expect("checker guarantees the relation exists");

    let mut arbitraries: Vec<String> = Vec::new(); // fc.integer(...) lines
    let mut param_names: Vec<String> = Vec::new(); // arrow-fn params, in order
    let mut constructs: Vec<String> = Vec::new(); // `const a = {...};`
    let mut call_args: Vec<String> = Vec::new(); // values passed to the impl

    for (arg, param) in law.args.iter().zip(&relation.params) {
        let sort = sorts
            .get(param.sort.as_str())
            .expect("checker guarantees the sort exists");

        if sort.fields.is_empty() {
            // Identity sort: a bare number is the value.
            arbitraries.push(strategy_for(&Ty::Sort(sort.name.clone())).to_string());
            param_names.push(arg.clone());
            call_args.push(arg.clone());
        } else {
            let mut field_inits: Vec<String> = Vec::new();
            for field in &sort.fields {
                let pname = format!("{arg}_{}", field.name);
                arbitraries.push(strategy_for(&field.ty).to_string());
                param_names.push(pname.clone());
                field_inits.push(format!("{}: {pname}", field.name));
            }
            constructs.push(format!(
                "        const {arg} = {{ {} }};",
                field_inits.join(", ")
            ));
            call_args.push(arg.clone());
        }
    }

    let oracle = if law.clauses.is_empty() {
        "true".to_string()
    } else {
        law.clauses
            .iter()
            .map(clause_to_ts)
            .collect::<Vec<_>>()
            .join(" && ")
    };

    let mut body = String::new();
    body.push_str(&format!("test(\"law_{}\", () => {{\n", law.relation));
    body.push_str("  fc.assert(\n");
    body.push_str("    fc.property(\n");
    for arb in &arbitraries {
        body.push_str(&format!("      {arb},\n"));
    }
    body.push_str(&format!("      ({}) => {{\n", param_names.join(", ")));
    for c in &constructs {
        body.push_str(c);
        body.push('\n');
    }
    body.push_str(&format!("        const oracle = {oracle};\n"));
    body.push_str(&format!(
        "        const actual = sut.{}({});\n",
        law.relation,
        call_args.join(", ")
    ));
    body.push_str("        return actual === oracle;\n");
    body.push_str("      }\n");
    body.push_str("    )\n");
    body.push_str("  );\n");
    body.push_str("});\n\n");
    body
}

/// A fast-check arbitrary for a field type.
fn strategy_for(ty: &Ty) -> &'static str {
    match ty {
        Ty::Int => "fc.integer({ min: -20, max: 20 })",
        // No-field sort = an identity id in a tiny range, so collisions (and
        // thus law violations) are likely to be hit.
        Ty::Sort(_) => "fc.integer({ min: 0, max: 1 })",
    }
}

fn clause_to_ts(clause: &Clause) -> String {
    match clause {
        Clause::Compare(p) => pred_to_ts(p),
        // `antecedent => consequent` is logically `(!antecedent || consequent)`.
        Clause::Implies { ante, cons, .. } => {
            format!("(!{} || {})", pred_to_ts(ante), pred_to_ts(cons))
        }
    }
}

fn pred_to_ts(pred: &Pred) -> String {
    format!(
        "({} {} {})",
        expr_to_ts(&pred.lhs),
        op_to_ts(pred.op),
        expr_to_ts(&pred.rhs)
    )
}

fn expr_to_ts(expr: &Expr) -> String {
    match expr {
        Expr::Field { arg, field } => format!("{arg}.{field}"),
        Expr::Int(n) => format!("{n}"),
        Expr::Arg(name) => name.clone(),
    }
}

fn op_to_ts(op: CmpOp) -> &'static str {
    match op {
        CmpOp::Eq => "===",
        CmpOp::Le => "<=",
        CmpOp::Lt => "<",
        CmpOp::Ge => ">=",
        CmpOp::Gt => ">",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse;

    fn generate(src: &str, module: &str) -> String {
        let spec = parse(src).unwrap();
        TypeScriptBackend.emit(
            &spec,
            &EmitOptions {
                module: module.to_string(),
            },
        )
    }

    #[test]
    fn generates_expected_pieces_for_real_spec() {
        let src = include_str!("../../../../.hiker/temporal.tent");
        let code = generate(src, "temporal");

        assert!(code.contains("import fc from \"fast-check\";"));
        assert!(code.contains("import * as sut from \"temporal\";"));
        assert!(code.contains("test(\"law_point_in_interval\""));
        // object construction with the spec's field names
        assert!(code.contains("const p = { media: p_media, t: p_t };"));
        // oracle uses === for equality and reflects point-in-interval
        assert!(code.contains("(p.media === i.media) && (i.t0 <= p.t) && (p.t <= i.t1)"));
        // calls the impl through the sut namespace, by value
        assert!(code.contains("sut.point_in_interval(p, i)"));
        assert!(code.contains("return actual === oracle;"));
    }
}
