//! Committed shim so `cargo test` discovers the gitignored generated tests.
//!
//! The actual property tests live in `.hiker-cache/rust/generated.rs`, which
//! is regenerated by `hiker gen` and never committed. Because cargo only
//! finds integration tests under `tests/`, this one-line file pulls the cache
//! file in. Run `hiker gen` BEFORE `cargo test`, or this include fails
//! because the cache file does not exist yet.
include!("../../../.hiker-cache/rust/generated.rs");
