//! Committed shim so `cargo test` discovers the gitignored generated tests.
//!
//! The actual property tests live in `.rascador-cache/rust/generated.rs`, which
//! is regenerated by `rascador gen` and never committed. Because cargo only
//! finds integration tests under `tests/`, this one-line file pulls the cache
//! file in. Run `rascador gen` BEFORE `cargo test`, or this include fails
//! because the cache file does not exist yet.
include!("../../../.rascador-cache/rust/generated.rs");
